org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=misctweaks
mod.name=MiscTweaks
mod.group=me.pajic
mod.version=1.3.0
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=QoL additions and tweaks
mod.sources_url=https://github.com/pajicadvance/misctweaks
mod.homepage_url=https://modrinth.com/mod/misctweaks
mod.issues_url=https://github.com/pajicadvance/misctweaks/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=9sMkzzYU
publish.curseforge=1227334
publish.github=false
